### ISSUE TITLE
Cant load external images ?

### ISSUE THREAD

**Issue by LivHathaway** [Longwelwind/adventures#4]
Hi! I'm getting broken image icons in my text boxes instead of displaying the linked images.  Would that be fixed if I encoded my scene bgs in base64 or do I need to make em a specific size? Thanks so much, this is a really cool tool, I've spent a good few hours in it over the past few days!

**Comment by Longwelwind** [comment]
What kind of links are you using ? Does it begin with http(s) or file ? Could you please copy-paste where and how you try to include an image ?

**Comment by LivHathaway** [comment]
Absolutely! I was following this guide (linked at relevant time) https://youtu.be/-OutoYaRIp8?t=38

**Comment by Longwelwind** [comment]
Try this (it should display an image of a gray fog):

```<img src="https://longwelwind.net/assets/Selection_016.png" alt="Text that will be displayed if the image can't be displayed" />```

The `alt` attribute will be displayed instead of the image screen-reader devices.

**Comment by LivHathaway** [comment]
Works!! Thank you!

**Comment by Longwelwind** [comment]
Oh, damn, you can use this to resize the image:

```<img src="https://longwelwind.net/assets/Selection_016.png" alt="Text that will be displayed if the image can't be displayed" width="100px" height="100px" />```

You can also replace one of the `100px` by `auto` so that it automatically computes the size based on the other size to keep the aspect ratio.

**Comment by LivHathaway** [comment]
oh man that's very helpfull, thank you! Also, it did load the 200x500 version after I linked it from Imgbb, so looks like dropbox might be interacting weird. Easy to go around dropbox though. Thank you so much!
